config/routes.rb
Gradeual::Application.routes.draw do

  resources :assignments do
    resources :submissions, :only => [:new, :create]
  end

  resources :problem_sets

  resources :groups

  resources :problem_tests

  resources :problems do
    member do
      get :copy
    end
  end

  resources :submissions do
    member do
      get :download_bundle
    end
  end

  devise_for :students, :controllers => { :omniauth_callbacks => "students/omniauth_callbacks" }

  devise_for :teachers

  resources :students, :only => [:index, :show]

  root :to => "home#index"
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :group
  belongs_to :problem_set
  belongs_to :problem
  after_initialize :init_dates
  attr_accessible :due_at, :start_at, :value, :problem_id, :group_id, :problem_set_id
  validate :start_at_before_due_at
  #validates_numericality_of :value, :greater_than_or_equal => 0
  
  def past_due?
    Time.new >= due_at
  end
  
  def started?
    Time.new >= start_at
  end
  
  def to_s
    problem.name
  end

  protected
  def init_dates
    self.start_at ||= DateTime.tomorrow.beginning_of_day
    self.due_at ||= DateTime.tomorrow.end_of_day
  end

  def start_at_before_due_at
    errors.add :start_at, :cant_be_after_due_at if start_at > due_at
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < InheritedResources::Base
  before_filter :authenticate_teacher!
  before_filter :fix_time_params, :only => [:create, :update]

  def create
    @assignment = Assignment.new(params[:assignment])
    @assignment.value = @assignment.problem.default_value if @assignment.value.blank?
    @assignment.teacher = current_teacher
    create!
  end

  protected

  def beginning_of_association_chain
    current_teacher
  end

  def fix_time_params
    [:start_at, :due_at].each do |param|
      date = Date.parse(params.delete(param))
      params[:assignment].merge!({
                      "#{param}(1i)" => date.year.to_s,
                      "#{param}(2i)" => date.month.to_s,
                      "#{param}(3i)" => date.day.to_s
                    })
    end
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= render :partial => "shared/generic_errors", :locals => { :object => @assignment } %>

<%= form_for(@assignment, :html => { :class => "form-horizontal" }) do |form| %>
  <fieldset>
    <% if @assignment.errors.any? %>
      <div class="alert">
        <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this @assignment from being saved:</h2>
        <ul>
          <% @assignment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= form.label :problem_id, :class => "control-label" %>
      <div class="controls">
        <%= form.collection_select :problem_id, Problem.all, :id, :name, :prompt => true %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :value, :class => "control-label" %>
      <div class="controls">
        <%= form.text_field :value %> <%= @assignment.problem ? "Default value (#{@assignment.problem.default_value})" : " (Leave blank for default)" %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :start_at, :class => "control-label" %>
      <div class="controls date start">
        <%= text_field_tag :start_at, @assignment.start_at.try(:to_date), :class => "datepicker"  %>
        <%= form.time_select :start_at, :ignore_date => true %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :due_at, :class => "control-label" %>
      <div class="controls date end">
        <%= text_field_tag :due_at, @assignment.due_at.try(:to_date), :class => "datepicker"  %>
        <%= form.time_select :due_at, :ignore_date => true %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :group_id, :class => "control-label" %>
      <div class="controls">
        <%= form.collection_select :group_id, Group.all, :id, :name, :prompt => true %>
      </div>
    </div>
    <div class="control-group">
      <%= form.label :problem_set_id, :class => "control-label" %>
      <div class="controls">
        <%= form.collection_select :problem_set_id, Group.all, :id, :name, :prompt => true %>
      </div>
    </div>

    <div class="form-actions">
      <button class="btn btn-primary" name="commit" type="submit">Save</button>
      <%= link_to "Cancel", assignments_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>

<%= render :partial => "form" %>

app/views/assignments/index.html.erb
<h1>Assignments</h1>
<%= link_to "New", new_assignment_path, :class => "btn btn-primary" %>
<br />

<div class="assignments">
<ul>
  <% @assignments.each do |assignment| %>
    <li>
		<%= link_to "#{assignment.problem.name} for #{assignment.group}", assignment_path(assignment), :class=>"view-link" %> |
		<%= link_to "Edit", edit_assignment_path(assignment) %> |
		<%= link_to "Delete", assignment_path(assignment), :method => :delete %>
    </li>
  <% end %>
</ul>
</div>

app/views/assignments/new.html.erb
<h1>New Problem Set</h1>

<%= render :partial => "form" %>

app/views/assignments/show.html.erb
<h1> <%= @assignment.problem.name %></h1>
<p>
<%= link_to "Edit", edit_assignment_path(@assignment) %> |
<%= link_to "Delete", assignment_path(@assignment), :method => :delete %> |
<%= link_to "Back", assignments_path %>
</p>

<h3>Starts</h3>
<div class="well well-small">
  <p><%= @assignment.start_at.to_s :short %></p>
</div>

<h3>Due</h3>
<div class="well well-small">
  <p><%= @assignment.due_at.to_s :short %></p>
</div>

<h3>Value</h3>
<div class="well well-small">
  <p><%= @assignment.value %></p>
</div>

<h2>Problem details</h2>
<%= render :partial => "shared/problem_show", :locals => {:problem => @assignment.problem} %>

<div class="form-actions">
  <%= link_to "Back", assignments_path, :class => "btn" %>
</div>