config/routes.rb
Gradeual::Application.routes.draw do

  resources :assignments do
    resources :submissions, :only => [:new, :create]
  end

  resources :problem_sets

  resources :groups

  resources :problem_tests

  resources :problems do
    member do
      get :copy
    end
  end

  resources :submissions do
    member do
      get :download_bundle
    end
  end

  devise_for :students, :controllers => { :omniauth_callbacks => "students/omniauth_callbacks" }

  devise_for :teachers

  resources :students, :only => [:index, :show]

  root :to => "home#index"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer          not null, primary key
#  teacher_id  :integer
#  name        :string(255)
#  description :string(255)
#  tags        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Group < ActiveRecord::Base
  belongs_to :teacher
  has_many :student_groups
  has_many :students, :through => :student_groups
  has_many :assignments
  has_many :problems, :through => :assignments
  attr_accessible :description, :name, :tags, :student_ids, :problem_ids, :assignment_ids
  
  def to_s
    "#{name}: #{description}"
  end
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :submissions
  has_many :student_groups
  has_many :groups, :through => :student_groups
  has_many :group_assignments, :through => :groups
  has_many :submission_assignments, :through => :submissions
  has_many :problems, :through => :groups

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    student = Student.where(:email => data["email"]).first

    unless student
      student = Student.create(email: data["email"], password: Devise.friendly_token[0,20])
    end
    student
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def to_s
    "#{full_name}: #{email}"
  end
end

app/controllers/groups_controller.rb
class GroupsController < InheritedResources::Base
  before_filter :authenticate_teacher!

  def beginning_of_association_chain
    current_teacher
  end
  
  def create
    @group = Group.new(params[:group])
    @group.teacher = current_teacher
    create!
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= render :partial => "shared/generic_errors", :locals => { :object => @group } %>

<%= form_for(@group, :html => { :class => "form-horizontal" }) do |form| %>
  <fieldset>
    <div class="control-group">
      <%= form.label :name, :class => "control-label" %>
      <div class="controls">
        <%= form.text_field :name %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :description, :class => "control-label" %>
      <div class="controls">
        <%= form.text_field :description %>
      </div>
    </div>

    <div class="control-group">
      <%= form.label :tags, :class => "control-label" %>
      <div class="controls">
        <%= form.text_field :tags %>
      </div>
    </div>

    <div class="control-group">
		<%= form.label :students, :class => "control-label" %>
		<% Student.all.each do |student| %>
		<div class="controls">
			<%= check_box_tag 'group[student_ids][]', student.id, @group.students.include?(student) %>
			<%= student %>
		</div>
		<% end %>
	</div>

    <div class="control-group">
		<%= form.label :problems, :class => "control-label" %>
		<% Problem.all.each do |problem| %>
		<div class="controls">
			<%= check_box_tag 'group[problem_ids][]', problem.id, @group.problems.include?(problem) %>
			<%= problem %>
		</div>
		<% end %>
	</div>
	

	<div class="control-group">
		<%= link_to "New problem",  new_problem_path, :class=>"control-btn" %>
	</div>

    <div class="form-actions">
      <button class="btn btn-primary" name="commit" type="submit">Save</button>
      <%= link_to "Cancel", groups_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render :partial => "form" %>

app/views/groups/index.html.erb
<h1>Groups</h1>
<%= link_to "New", new_group_path, :class => "btn btn-primary" %></p>
<br />

<ul>
  <% @groups.each do |group| %>
    <li>
		<%= link_to group.name, group_path(group), :class=>"view-link" %> |
		<%= link_to "Edit", edit_group_path(group) %> |
		<%= link_to "Delete", group_path(group), :method => :delete %> 
    </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<h1>New Group</h1>
<p>Define a new group</p>

<%= render :partial => "form" %>

app/views/groups/show.html.erb
<h1> <%= @group.name %></h1>
<p>
<%= link_to "Edit", edit_group_path(@group) %> |
<%= link_to "Delete", group_path(@group), :method => :delete %> |
<%= link_to "New", new_group_path %> |
<%= link_to "Back", groups_path %>
</p>

<h3>Description</h3>
<div class="well well-small">
  <p> <%= @group.description %></p>
</div>

<h3>Tags</h3>
<div class="well well-small">
  <p> <%= @group.tags %></p>
</div>

<h3>Students</h3>
<div class="well well-small">
<ul>
	<% @group.students.each do |student| %>
	<li><%= student %></li>
	<% end %>
</ul>
</div>

<h3>Assignments</h3>
<div class="well well-small">
<ul>
	<% @group.assignments.each do |assignment| %>
	<li><%= link_to assignment, assignment_path(assignment) %> | Starts: <%= assignment.start_at %> | Due <%= assignment.due_at %> | Value: <%= assignment.value %> | <%= link_to "Edit", edit_assignment_path(assignment) %> | <%= link_to "Delete", assignment_path(assignment), :method => :delete %></li>
	<% end %>
</ul>
</div>

<div class="form-actions">
  <%= link_to "Back", groups_path, :class => "btn" %>

  <%= link_to "Edit", edit_group_path(@group), :class => "btn" %>
</div>