config/routes.rb
Gradeual::Application.routes.draw do

  resources :assignments do
    resources :submissions, :only => [:new, :create]
  end

  resources :problem_sets

  resources :groups

  resources :problem_tests

  resources :problems do
    member do
      get :copy
    end
  end

  resources :submissions do
    member do
      get :download_bundle
    end
  end

  devise_for :students, :controllers => { :omniauth_callbacks => "students/omniauth_callbacks" }

  devise_for :teachers

  resources :students, :only => [:index, :show]

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_teacher
      teacher
    elsif current_student
      student
    end  
      
  end
  
  protected
  
  def teacher
    @groups = Group.all
    render :teacher
  end
  
  def student
    @student = current_student
    @groups = current_student.groups
    render :student
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="home2">
  <h1>Welcome to Codakata!</h1>
  <p>Do your homework!</p>
  <br>
  <%= link_to "Log in", new_student_session_path, :class => "btn btn-warning btn-large" %>
</div>
<div class="home3 container">
  <p class="lead">
  <blockquote class="pull-left">
    <p>Russ told me to do my homework, so I did.  I was so surprised to find out that I actually learned!</p>
    <small>Anonymous Student</small>
  </blockquote>

  <br />
  <br />

  <blockquote class="pull-right">
    <p>I used to wait until the last day to do my homework.  Now I do it every day, I feel so much smarter!</p>
    <small>Anonymous Student</small>
  </blockquote>

  </p>
</div>

app/views/home/student.html.erb
<div class="container">
  <h1>Welcome <%= @student.first_name %></h1>
  <p>See upcoming assignments, your solutions and more.</p>
  <div>
    <% @groups.each do |group| %>
      <div class="well">
        <h3><%= group.to_s %></h3>
        <h4>Problems: <%= group.problems.count %></h4>
        <p>
        <% group.assignments.sort_by.each_with_index do |assignment, index| %>
          <%= link_to assignment, new_assignment_submission_path(assignment) %><%= "," unless index == group.assignments.size - 1 %>
        <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/home/teacher.html.erb
<div class="container">
  <h1>Welcome teacher!</h1>
  <p>You can start managing your groups, students and problems here.</p>
  <div>
    <% @groups.each do |group| %>
      <div class="well">
        <h3><%= link_to group.to_s, group_path(group) %></h3>
        <h4>Students: <%= group.students.count %></h4>
        <p>
        <% group.students.each_with_index do |student, index| %>
          <%= link_to student.full_name, student_path(student) %><%= "," unless index == group.students.size - 1 %>
        <% end %>
        </p>
        <h4>Problems: <%= group.problems.count %></h4>
        <p>
        <% group.problems.each_with_index do |problem, index| %>
          <%= link_to problem, problem_path(problem) %><%= "," unless index == group.problems.size - 1 %>
        <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>