config/routes.rb
Gradeual::Application.routes.draw do

  resources :assignments do
    resources :submissions, :only => [:new, :create]
  end

  resources :problem_sets

  resources :groups

  resources :problem_tests

  resources :problems do
    member do
      get :copy
    end
  end

  resources :submissions do
    member do
      get :download_bundle
    end
  end

  devise_for :students, :controllers => { :omniauth_callbacks => "students/omniauth_callbacks" }

  devise_for :teachers

  resources :students, :only => [:index, :show]

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codoka</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="shadow navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<%= root_url %>">Codoka</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <% if teacher_signed_in? %>
                <li class=""><a href="<%= problems_path %>">Problems</a></li>
                <li class=""><a href="<%= assignments_path %>">Assignments</a></li>
                <li class=""><a href="<%= students_path %>">Students</a></li>
                <li class=""><a href="<%= groups_path %>">Groups</a></li>
              <% end %>
            </ul>
          </div>
          <ul class="nav pull-right">
            <% if student_signed_in? %>
              <li><%= link_to "Sign Out", destroy_student_session_path, :method => :delete %></li>
              <li><%= link_to "My Account", edit_student_registration_path %></li>
            <% elsif teacher_signed_in? %>
              <li><%= link_to "Sign Out", destroy_teacher_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Student Sign In", new_student_session_path %></li>
              <li><%= link_to "Teacher Sign In", new_teacher_session_path %></li>
            <% end %>
            <li class="student-login">
          </ul>
        </div>
      </div>
    </div>

    <div id="container" class="<%= controller_name %> container">
      <div class="container">
        <% if notice.present? %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= notice %>
          </div>
        <% end %>
        <% if alert.present? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= alert %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>

  </body>

  <%= javascript_include_tag "application" %>
</html>